apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Desafio-jackexperts</title>
    </head>
    <body>
        <h1>Desafio-experts</h1>
    </body>
    </html>

