apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app
  labels:
    desafio: jackexperts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
        desafio: jackexperts
    spec:
      containers:
      - name: meu-container
        image: felipedevopss/desafio-jackexpertss:latest # 
        ports:
        - containerPort: 80
        securityContext:
          runAsUser: 1000  # Altere para um usuário não-root

